### ISSUE TITLE
iOS Sim error on button

### ISSUE THREAD

**Issue by kraftmedia** [sattasundar/Xamarin.Forms-Firebase-PhoneAuth#1]
is it possible to make the readme bit more clear I am using an iOS simulator I have dropped in my googleservices-info.plist what build setting should this be? when I enter my number and press submit it pops up this error:

Objective-C exception thrown. Name: NSInternalInconsistencyException Reason: the default FIRApp instance must be configured before the default FIRAuthinstance can be initialised.

does something need to be in the app delegate file or any other installation?

thanks

**Comment by sattasundar** [comment]
@kraftmedia Looking into this. Can you provide me your sample for debugging? if possible.

**Comment by sattasundar** [comment]
@kraftmedia 
Your app delegate file should be look like this;

        public override bool FinishedLaunching(UIApplication app, NSDictionary options)
        {
            global::Xamarin.Forms.Forms.Init();
            Xamarin.Forms.FormsMaterial.Init();
            XF.Material.iOS.Material.Init();
            CrossFirebase.Initialize(app, options, CreateCrossFirebaseSettings());
            LoadApplication(new App());

            return base.FinishedLaunching(app, options);
        }

        private CrossFirebaseSettings CreateCrossFirebaseSettings()
        {
            return new CrossFirebaseSettings(
               isAnalyticsEnabled: true,
               isAuthEnabled: true,
               isCloudMessagingEnabled: true,
               isDynamicLinksEnabled: true,
               isFirestoreEnabled: true,
               isFunctionsEnabled: true,
               isRemoteConfigEnabled: true,
               isStorageEnabled: true,
               facebookId: "",//set facebook id created for app
               facebookAppName: "",//app name
               googleRequestIdToken: "" //set google request id
               );
        }

**Comment by sattasundar** [comment]
- Doc (README.md) updated. 
- Pushed Code and configuration changes.

**Comment by sattasundar** [comment]
@kraftmedia  any update? is it working for you?

**Comment by sattasundar** [comment]
Closing this.

Thanks :-)
